insert into autores values (1,'Sophia Angelides',null);
insert into autores values (2,'Mário Pedrosa',null);
insert into autores values (1002,'Otília Arantes',null);
insert into autores values (3,'Emílio F. Moran',null);
insert into autores values (4,'Jack R. Greene',null);
insert into autores values (5,'Antônio Chaves',null);
insert into autores values (6,'José Pedro de Oliveira Costa',null);
insert into autores values (7,'Ana Mae Barbosa',null);
insert into autores values (8,'Piero Comin-Chiaramonti',null);
insert into autores values (1008,'Celso Gomes',null);
insert into autores values (9,'Barão de Itararé',null);
insert into autores values (10,'Barão de Itararé',null);
insert into autores values (11,'Aziz Nacib AbSaber',null);
insert into autores values (12,'Maria L. Aragão',null);
insert into autores values (1012,'José Carlos S. Meihy ',null);
insert into autores values (13,'Eliane Garcindo Dayrell',null);
insert into autores values (1013,'Zilda Márcia Iokoi',null);
insert into autores values (14,'Maria Lígia Coelho Prado',null);
insert into autores values (15,'Tânia Maria Bessone',null);
insert into autores values (1015,'Tereza Aline Queiroz',null);
insert into autores values (16,'Dante Moreira Leite',null);
insert into autores values (17,'Nilza Nunes da Silva',null);
insert into autores values (18,'Ricardo Palma',null);
insert into autores values (19,'José Luiz Goldfarb',null);
insert into autores values (1019,'Márcia Ferraz',null);
insert into autores values (20,'Júlio César Rodrigues Pereira',null);